import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google"; // Adicionando Inter
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",  // Variável para a fonte Inter
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Adm Academia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`} // Adicionando a fonte Inter aqui
      >
        {children}
      </body>
    </html>
  );
}
